// Code generated by counterfeiter. DO NOT EDIT.
package librarytesting

import (
	"sync"

	library "github.com/MarioCarrion/videos/counterfeiter"
)

type FakeBookStore struct {
	CreateStub        func(string, library.Details) (library.Book, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 string
		arg2 library.Details
	}
	createReturns struct {
		result1 library.Book
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 library.Book
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBookStore) Create(arg1 string, arg2 library.Details) (library.Book, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 string
		arg2 library.Details
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBookStore) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeBookStore) CreateCalls(stub func(string, library.Details) (library.Book, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeBookStore) CreateArgsForCall(i int) (string, library.Details) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBookStore) CreateReturns(result1 library.Book, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 library.Book
		result2 error
	}{result1, result2}
}

func (fake *FakeBookStore) CreateReturnsOnCall(i int, result1 library.Book, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 library.Book
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 library.Book
		result2 error
	}{result1, result2}
}

func (fake *FakeBookStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBookStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ library.BookStore = new(FakeBookStore)
