swagger: "2.0"
info:
  title: users API
  version: 0.0.1
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /openapi3.json:
    get:
      tags:
      - users
      summary: Download ./gen/http/openapi3.json
      operationId: users#/openapi3.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /users:
    get:
      tags:
      - users
      summary: all users
      operationId: users#all
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/UserResponse'
      schemes:
      - http
    post:
      tags:
      - users
      summary: create users
      operationId: users#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UsersCreateRequestBody'
          required:
          - name
          - birth_year
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UsersCreateResponseBody'
            required:
            - name
            - birth_year
      schemes:
      - http
definitions:
  UserResponse:
    title: UserResponse
    type: object
    properties:
      birth_year:
        type: integer
        example: 1962
        minimum: 1900
        maximum: 2022
      name:
        type: string
        example: skl
        minLength: 5
    example:
      birth_year: 1930
      name: or2
    required:
    - name
    - birth_year
  UsersCreateRequestBody:
    title: UsersCreateRequestBody
    type: object
    properties:
      birth_year:
        type: integer
        example: 1968
        minimum: 1900
        maximum: 2022
      name:
        type: string
        example: vc0
        minLength: 5
    example:
      birth_year: 1904
      name: 3su
    required:
    - name
    - birth_year
  UsersCreateResponseBody:
    title: UsersCreateResponseBody
    type: object
    properties:
      birth_year:
        type: integer
        example: 2014
        minimum: 1900
        maximum: 2022
      name:
        type: string
        example: 8za
        minLength: 5
    example:
      birth_year: 1992
      name: nwj
    required:
    - name
    - birth_year
