// Code generated by sqlc. DO NOT EDIT.

package main

import (
	"database/sql"
)

type Names struct {
	Nconst             sql.NullString
	PrimaryName        sql.NullString
	BirthYear          sql.NullString
	DeathYear          sql.NullString
	PrimaryProfessions []string
	KnownForTitles     []string
}
