// Code generated by sqlc. DO NOT EDIT.
// source: names.sql

package main

import (
	"context"
	"database/sql"
)

const selectName = `-- name: SelectName :one
SELECT
  nconst,
  primary_name,
  birth_year,
  death_year
FROM
  names
WHERE
  nconst = $1
LIMIT 1
`

type SelectNameRow struct {
	Nconst      sql.NullString
	PrimaryName sql.NullString
	BirthYear   sql.NullString
	DeathYear   sql.NullString
}

func (q *Queries) SelectName(ctx context.Context, nconst sql.NullString) (SelectNameRow, error) {
	row := q.db.QueryRowContext(ctx, selectName, nconst)
	var i SelectNameRow
	err := row.Scan(
		&i.Nconst,
		&i.PrimaryName,
		&i.BirthYear,
		&i.DeathYear,
	)
	return i, err
}
