require("plugins.setup")

require("plugins.default")

require("plugins.lualine")
require("plugins.barbar")
require("plugins.nvim-tree")
require("plugins.comment")
require("plugins.telescope")
require("plugins.nvim-treesitter")
require("plugins.gitsigns")
require("plugins.nvim-cmp")
require("plugins.catppuccin-theme")
require("plugins.nvim-surround")
require("plugins.go")
require("plugins.navigator")
