// Code generated by "stringer -type=Country"; DO NOT EDIT.

package skip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[USA-0]
	_ = x[Mexico-1]
	_ = x[Phillipines-2]
}

const _Country_name = "USAMexicoPhillipines"

var _Country_index = [...]uint8{0, 3, 9, 20}

func (i Country) String() string {
	if i < 0 || i >= Country(len(_Country_index)-1) {
		return "Country(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Country_name[_Country_index[i]:_Country_index[i+1]]
}
